site_name: 'CiviHR user guide'
site_url: http://civihr.org
repo_url: https://github.com/compucorp/civihr-docs.git
site_description: 'A guide for users and administrators of CiviHR.'
site_author: 'The CiviHR community'


theme: readthedocs

pages:
- Home: 'index.md'
- Introduction:
    - 'What is CiviHR?': 'introduction/what-is-civihr.md'
    - 'Components of CiviHR': 'introduction/components-of-civihr.md'
