site_name: 'CiviHR user guide'
site_url: http://civihr.org
repo_url: https://github.com/compucorp/civihr-docs.git
site_description: 'A guide for users and administrators of CiviHR.'
site_author: 'The CiviHR community'


theme: readthedocs

pages:
- Home: 'index.md'
- Introduction:
    - 'What is CiviHR?': 'introduction/what-is-civihr.md'
    - 'Components of CiviHR': 'introduction/components-of-civihr.md'
- Initial setup and configuration:
    - 'Initial setup and configuration': 'initial-setup-and-configuration/Initial-setup-and-configuration.md'
    - 'Localise CiviHR': 'initial-setup-and-configuration/localise-civihr.md'
    - 'Customise the user interface': 'initial-setup-and-configuration/customise-the-user-interface.md'
    - 'Add funders and insurance providers': 'initial-setup-and-configuration/add-funders-and-insurance-providers.md'
    - 'Component-level configuration': 'initial-setup-and-configuration/component-level-configuration.md'
    - 'Advanced configuration checklist for service providers': 'initial-setup-and-configuration/advanced-configuration-checklist-for-service-providers.md'    
- Staff Profile:
    - 'Staff Profile': 'staff/staff-profile.md'
    - 'Contact Summary': 'staff/contact-summary.md'
    - 'Job Contract': 'staff/job-contract.md'
    - 'Job Roles': 'staff/job-roles.md'
    - 'Personal Details': 'staff/personal-details.md'
    - 'Absences': 'staff/absences.md'
    - 'Tasks': 'staff/tasks.md'
    - 'Identification': 'staff/identification.md'
    - 'Emergency Contacts': 'staff/emergency-contacts.md'
    - 'Managers': 'staff/managers.md'
    - 'Bank Details': 'staff/bank-details.md'
    - 'Career History': 'staff/career-history.md'
    - 'Medical and Disability': 'staff/medical-and-disability.md'
    - 'Qualifications': 'staff/qualifications.md'
    - 'Notes': 'staff/notes.md'
    - 'Change Log': 'staff/change-log.md'
- Tasks and Reminders:
    - 'Tasks and Reminders': 'task-and-reminders/tasks-and-reminders.md'
    - 'Schedule and delegate tasks': 'task-and-reminders/schedule-and-delegate-tasks.md'
    - 'Follow up with quick reminders': 'task-and-reminders/follow-up-with-quick-reminders.md'
    - 'Manage joining, exiting, contract renewals': 'task-and-reminders/manage-joining-exiting-contract-renewals.md'
- Leave and Absences:
    - 'Leave and Absences': 'leave-and-absences/leave-and-absences.md'
- Recruitment (ATS):
    - 'Recruitment (ATS)': 'recruitment/recruitment.md'
    - 'Vacancies Dashboard': 'recruitment/vacancies-dashboard.md'
    - 'Vacancies Pipeline': 'recruitment/vacancies-pipeline.md'
- Self Service Portal:
    - 'Login screen': 'self-sercive-portal/login-screen.md'
    - 'My Details': 'self-sercive-portal/my-details.md'
    - 'My Tasks': 'self-sercive-portal/my-tasks.md'
    - 'My Leave': 'self-sercive-portal/my-leave.md'
    - 'My Sickness': 'self-sercive-portal/my-sickness.md'
    - 'Manager Leave Approval': 'self-sercive-portal/manager-leave-approval.md'    
    - 'HR Resources': 'self-sercive-portal/hr-resources.md'
    - 'Staff Directory': 'self-sercive-portal/staff-directory.md'
    - 'Vacancies': 'self-sercive-portal/vacancies.md'
    - 'Reports for HR Administrators': 'self-sercive-portal/reports-for-hr-administrators.md'
    - 'Create login accounts for Self Service Portal': 'self-sercive-portal/create-login-accounts-for-self-service-portal.md'
- Self Service Portal:
    - 'Importing staff data': 'importing-staff-data/importing-staff-data.md'
    - 'Get to know CiviHR fields': 'importing-staff-data/get-to-know-civihr-fields.md'
    - 'Review existing data': 'importing-staff-data/review-existing-data.md'
    - 'Prepare data for import': 'importing-staff-data/prepare-data-for-import.md'
    - 'Run a test import': 'importing-staff-data/run-a-test-import.md'
    - 'Run the full import': 'importing-staff-data/run-the-full-import.md'
    
- Reporting bugs:
    - 'Run the full import': 'reporting-bugs/reporting-bugs.md'  
